# CI项目名称
name: AP8220

# CI 触发计划
on:
  # 自动编译：当 Auto-Clean 运行完成后触发
  workflow_run:
    workflows: ["Auto-Clean"]
    types:
      - completed
  # 手动编译触发
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'
        required: false
        type: boolean

# CI 权限设置
permissions: write-all

# CI 任务配置
jobs:
  config:
    name: ${{matrix.CONFIG}}
    strategy:
      fail-fast: false
      matrix:
        # 指定编译机型配置
        CONFIG: [aliyun_ap8220]
        # 使用您指定的 ImmortalWrt 源码仓库
        SOURCE: [VIKINGYFY/immortalwrt]
        BRANCH: [main]

    # 调用您的公用编译核心 WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      # 对应您仓库中的 ap8220.txt 配置文件
      WRT_CONFIG: ${{matrix.CONFIG}}
      # 默认主题（settings.sh 会强制生效）
      WRT_THEME: argon
      # 默认主机名 (AP 模式建议区分)
      WRT_NAME: AP8220
      # 默认 SSID
      WRT_SSID: AP8220_WiFi
      # 默认 WiFi 密码
      WRT_WORD: 12345678
      # 默认后台地址 (建议与旁路由 192.168.10.1 区分，避免冲突)
      WRT_IP: 192.168.10.2
      # 源码配置
      WRT_REPO: github.com{{matrix.SOURCE}}.git
      WRT_BRANCH: ${{matrix.BRANCH}}
      WRT_SOURCE: ${{matrix.SOURCE}}
      # 插件调整参数
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      # 仅输出配置文件选项
      WRT_TEST: ${{inputs.TEST}}
