# CI项目名称
name: AP8220

# CI 触发计划
on:
  workflow_run:
    workflows: ["Auto-Clean"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件'
        default: 'false'
        required: false
        type: boolean

permissions: write-all

jobs:
  config:
    name: ${{matrix.CONFIG}}
    strategy:
      fail-fast: false
      matrix:
        # 确保这个名字和你仓库里的 .txt 文件名一致
        CONFIG: [AP8220] 
        SOURCE: [VIKINGYFY/immortalwrt]
        BRANCH: [main]

    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_CONFIG: ${{matrix.CONFIG}}
      WRT_THEME: argon
      WRT_NAME: AP8220
      WRT_PW: 无
      WRT_SSID: AP8220_WiFi
      WRT_WORD: 12345678
      WRT_IP: 192.168.10.2
      # 修正了这里的链接格式
      WRT_REPO: github.com{{ matrix.SOURCE }}.git
      WRT_BRANCH: ${{ matrix.BRANCH }}
      WRT_SOURCE: ${{ matrix.SOURCE }}
      WRT_PACKAGE: ${{ inputs.PACKAGE }}
      WRT_TEST: ${{ inputs.TEST }}
